### ISSUE TITLE
Game completion speedup

### ISSUE THREAD

**Issue by coolchess123** [coolchess123/CCC-feedback#28]
CCC has a nice idea to speed up the endgame.

But its not fair on the engine with more time. I would suggest reducing the time of engine to 1/3 of what it has currently and leaving the increment as it is

If X has 9 mins left and Y has 3 mins left, currently its reduce to 10 second each. Lot of engines miss wins because of this

So lets make it X remaining time to 9/3 = 3 mins and Y to 3/3 = 1 min

**Comment by coolchess123** [comment]
I am in favor of eliminating this totally as Lc0 does not troll any more and games do end faster

**Comment by Khagrin2** [comment]
I agree ... the "go bullet" should just be eliminated.

**Comment by coolchess123** [comment]
Erik we need to get rid of it, many in Lc0 discord also want it removed

**Comment by chesserik** [comment]
I won’t get rid of it, but we will see if we can adjust it.

**Comment by chesserik** [comment]
What if we changed it to 1 min, + 2 seconds increment?

**Comment by coolchess123** [comment]
The logic is the engine with better time management should not be penalized

Easiest to implement and fair is divide the remaining time /3 for both engines and change increments to 2

**Comment by coolchess123** [comment]
Or make the eval as +10 before the speed up kicks in, having both engines +10 for 4 plies is 99.99% a win

**Comment by Khagrin2** [comment]
The main complaint, and why this is even an issue, is that an engine with considerable time has found a winning plan (i.e. the +5, agreed to by the other engine.) but ends up drawing because it is suddenly handicapped by "bullet" and is no longer able to find/execute that plan.   

Typically this "both > threshold for X moves" sort of thing would warrant adjudication, but viewers like to see the plan played out ... just quickly.  However, no solution that I can think of which reduces time for the engines is guaranteed to resolve the complaint _and_ satisfy the "win it quick" criteria.  

The current "bullet" is certainly not fair to an engine that may have a considerable time advantage.  Bumping the threshold to the suggested +10 and 4 ply is a good try.  The "divide time" idea may be fairer to the engines, but still won't guarantee "self-adjudication", i.e. a quick win.  

I don't know which is better ... maybe combining both would be efffective.  

The thing is, how does a Mod explain and justify such a complicated (and seemingly needless) mechanism to folks.  I really don't understand the argument for keeping any "speedup endgame" logic in place now that engine's don't "troll" much.  What's the rationale now?  I need to be able to offer a reasonable explanation to viewers/devs that ask.

What I do know:  (1) Most viewers are unaware of the current mechanism; (2) Many viewers find "trolling" to be oddly entertaining;  (2) Time controls at CCC are blitz and rapid.  Games will conclude in fairly short order without any mechanism in place.

That said, I maintain that trying to shorten a game at the expense of complexity and incurring the displeasure of engine authors seems unwarranted, so the easiest "fix" is to simply dump the notion.  I don't think this "bullet" drama is worth it since the engines are likely to end up in time control crunches anyway.

**Comment by chesserik** [comment]
Thanks. I think the issue, for me as a viewer, is when an engine is “lost”, and just spends TONS of time thinking about which “losing” move to play. I’ll think on this.

**Comment by coolchess123** [comment]
Lc0 trolls very less, so does Allie, so i think this issue is not such a big issue as earlier.

We need to finalize before c9 starts.

**Comment by chesserik** [comment]
It’s not just NN engines - even A/B engines take the full time thinking in lost positions.

**Comment by coolchess123** [comment]
Agreed, but say +8 for 6 plies for both engines and then reduce the time remaining to 1/3 of their respective times should make it really fast and fair

**Comment by coolchess123** [comment]
This needs to be addressed before C9, because once its decided, we cant change rules

**Comment by chesserik** [comment]
We moved to +8, and give 1 min. Let's see how this goes.

**Comment by coolchess123** [comment]
Nice, thanks

**Comment by coolchess123** [comment]
Just to clarify, if engine has < 1min left, i hope it wont get 1 minute?
