### ISSUE TITLE
Rules need rewording

### ISSUE THREAD

**Issue by coolchess123** [coolchess123/CCC-feedback#32]
Khag as discussed, kindly make it good to read and understand.

**Comment by chesserik** [comment]
?

**Comment by coolchess123** [comment]
The rules in the info section needs to be organized better. It is not very clear by reading them. I had requested Khagrin to give it a shot along with greco

**Comment by Khagrin2** [comment]
There are some rules which I (or viewers) don't fully understand, or that I expect need revision.  

I don't make the rules, but if you can clarify **what you want** for the questions below, then I may be able to organize and clarify things a bit.   (Note that I don't think folks have really had many problems with the rules as is.  And, any such "clarification" will necessitate MORE space and what some may consider undo verbiage.)  

My questions ...

**Question 1**   Currently:  "Engine can be updated at any time!"  Is this still the policy?  It clearly hasn't been in practice.  Seems the new policy may be:  "Engine updates are only allowed between stages/events."

**Question 2**   Currently:  "If a neutral event, technical glitch unconnected to the engines, the game will be restarted, from move 1. " ... Is this still the policy?  

Given the new "resume" functionality, perhaps the policy is now closer to:  

"If white has played 5 or more moves (post book when forced lines are used in an event), a game is considered "official".  If a non-engine problem with a game occurs before the the required 5 moves (post book) have been played, then the game will be replayed from the start.  The same forced opening moves will be used in the replay when forced lines are being used.  

If a non-engine problem occurs during an "official" game then the game will be resumed rather than restarted.  The engine "on the move" at the time the problem occurred will make the first move in the resumed game.  An engine in a resumed game will have its clock set to the time it had remaining when the problem occurred  _plus one minute_.   

The scheduled time of any replay/resume is at the discretion of the event administrator.  

Non-engine problems include:  network failures, hardware failures, tournament software (CuteChess) issues, and wrongly set engine versions or configurations (i.e. deployed version or configuration does not match author's written specification)."

**Question 3**   Is the "crash" rule changing?  Or is it still simply:  "If a game ends unexpectedly due to an engine problem, i.e. "bug", the problematic engine will be considered to have resigned the game." 

Perhaps a new clause is also warranted, e.g. "If an engine repeatedly disrupts an event by "crashing", the event organizer may exercise discretion regarding disqualification of the engine.  If an engine is disqualified, all results recorded for the engine in the current stage/event will be nullified.  The participation of a disqualified engine in future stages/events is completely at the discretion of the tournament organizer."

**Question 4**   A final decision needs to be made regarding:  "Games scored +5 by both engines for 4 ply, will enter bullet mode. The time control will change to 10m+2s."

**Comment by chesserik** [comment]
Will update

**Comment by coolchess123** [comment]
Fixed, resp of Arun
