### ISSUE TITLE
Make a clear message "end of the book"

### ISSUE THREAD

**Issue by robertomil81mil** [coolchess123/CCC-feedback#36]
When I'm looking at the opening it's not easy to know when the book ends. Look at this example 1.e4 e5 f4, both engines are showing evaluations and this is supposed to be a "KGA" book.
![Screenshot_2019-06-08-19-21-20](https://user-images.githubusercontent.com/51243949/59153611-ff676c80-8a22-11e9-915a-6ac7bfdad21d.png)

**Comment by Khagrin2** [comment]
This would be a nice enhancement, and likely reasonably easy to accomplish.  For example you could simply have the forced move numbers and/or the forced moves in the main move list displayed with a different color, background or font style (e.g. italic).  Probably need the moves themselves as part of that "and/or" since forced lines sometimes end with a white move and sometimes end with a black move.

**Comment by robertomil81mil** [comment]
Maybe a red color or blue

**Comment by coolchess123** [comment]
Make it a different color which is readable under black background

**Comment by robertomil81mil** [comment]
Thanks guys!
